name: Docker Image
on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'
      - 'CODEOWNERS'
    branches:
      - master
env:
  BASE_IMAGE: ghcr.io/${{ github.repository }}
  GITHUB_USERNAME: x-access-token
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  docker-deploy:
    name: Laste opp docker image
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v2
      - name: Sette opp Java
        uses: actions/setup-java@v2
        with:
          java-version: '11.x'
          distribution: 'adopt'

      - name: Bygge JAR
        run: ./mvnw clean package -DskipTests --settings ./.m2/settings.xml

      - name: Bygg & last opp Docker image
        run: |
          docker build . --pull --tag $BASE_IMAGE:latest
          echo "$GITHUB_TOKEN" | docker login --username ${GITHUB_REPOSITORY} --password-stdin ghcr.io
          docker push $BASE_IMAGE:latest
